M48
; DRILL file {KiCad (6.0.2)} date Wed Mar 16 17:45:18 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-03-16T17:45:18-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0630
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0807
%
G90
G05
T2
X4.54Y-2.98
T1
G00X4.54Y-3.1454
M15
G01X4.54Y-3.169
M16
G05
T0
M30
